GET travelers.cqlz5glh6vqe.us-east-1.rds.amazonaws.com/users

###
POST travelers.cqlz5glh6vqe.us-east-1.rds.amazonaws.com/users
Content-Type: application/json

{
    "username": "lfuen",
    "password": "&>K--n?OlR(Bfs9%4N6pPlTLeiqe"
}

z
###
GET travelers.cqlz5glh6vqe.us-east-1.rds.amazonaws.com/guides



###
POST travelers.cqlz5glh6vqe.us-east-1.rds.amazonaws.com/guides
Content-Type: application/json


